### ISSUE TITLE
Send Me Parts Needed For Midwest

### ISSUE THREAD

**Issue by SethKitchen** [SethKitchen/RocketDesignTeamAgilePlans#17]
Who: Leads to Seth
What: Send me any parts you need for midwest power (ie radio and receiver and thermocouples and etc)
When: Before First Meeting
Where: Internets
Why: Trying to get a budget for to give to Jeff

**Comment by ghost** [comment]
RF Transmitter Module
http://store.rfdesign.com.au/rfd-900p-modem/

**Comment by SethKitchen** [comment]
Transmitter=99.50,
Mixer= 750 New but rocketry forum $200, 
Resin | 105-1G (126 oz.) | 01-00354 | $98.26
Fast Hardener | 205-QT (27 oz.) | 01-00357 | $52.70
Slow Hardener | 206-QT (27 oz.) | 01-00360 | $44.29

**Comment by SethKitchen** [comment]
$350 strain gauges
$600 propellant

**Comment by SethKitchen** [comment]
~1750 total

**Comment by CRobless** [comment]
You forgot to add the cost for motor parts. ~250 for 54mm testing, ~300 for nikomedes

**Comment by SethKitchen** [comment]
Good call thanks. ~2300 total
