### ISSUE TITLE
Mine Safety Training

### ISSUE THREAD

**Issue by SethKitchen** [SethKitchen/RocketDesignTeamAgilePlans#2]
Who: At least 15 People
What: Trained in Mine Safety.
When: 9/3-9/17
Where: Missouri S&T Mine
Why: We need it to mix and test motors
How: Set up an appointment with the Mine, get members to sign up, carpool

**Comment by Usman-B** [comment]
Got it!

**Comment by AndyManson** [comment]
Got it!

**Comment by CRobless** [comment]
Training will not be happening this week or next, as the mine is too busy. This will probably need to be moved to the second and third sprints.

**Comment by SethKitchen** [comment]
Set for Friday September 29 at 2. Meet at SDELC a bit before for carpooling.
