### ISSUE TITLE
Research Aerospike Designs And Other Heat Resistive/Bow Shock Shifting Nose Cone Designs

### ISSUE THREAD

**Issue by SethKitchen** [SethKitchen/RocketDesignTeamAgilePlans#27]
Who: Several people on D&M
What: Look at types of Aerospike shapes and sizes for Mach 3.5-4. Find equations. Do a write-up.
When: First Sprint
Where: Internet SDELC professors (Hosder)
Why: We need an aerospike to reduce drag and heat on nosecone caused by high speed.

**Comment by appvf** [comment]
Sorry guys! Don't really know how to use github. I think I fixed it tho.
