### ISSUE TITLE
Training in General Safety

### ISSUE THREAD

**Issue by SethKitchen** [SethKitchen/RocketDesignTeamAgilePlans#3]
Who: Everyone on RDT
What: Finish General Safety Training through Canvas or through the SDELC.
When: 9/3-9/17
Where: SDELC or Internet
Why: To access the SDELC and Work Areas
How: Sign up on orgsync or canvas, show up and listen to Richard, or do the requirements online.

**Comment by SethKitchen** [comment]
Leave a little congrats to yourself when you finish :)

"Go me, I have General Safety!"

**Comment by davinschmied** [comment]
Go me I have gen safety, basic machine shop, and composites!

**Comment by Calebg720** [comment]
Go me, I have General Safety!

**Comment by AndyManson** [comment]
Go me I have general safety

**Comment by dbfv8** [comment]
Go me, i have general safety

**Comment by willziehm** [comment]
go me, i have general safety!

**Comment by kczn6** [comment]
Go me, I have general safety training!

**Comment by jng6w3** [comment]
Go me, I have general safety training

**Comment by Usman-B** [comment]
Go me, I have General Safety!

**Comment by jawwm9** [comment]
Go me, I have General Safety!

**Comment by Josiah-Wade** [comment]
Hip hip hooray 
Hip hip hooray
I got general safety out of the way

**Comment by SethKitchen** [comment]
Nice poetry to my ears

**Comment by krshg6** [comment]
Go me, I have General Safety!

**Comment by trevoraldenberg** [comment]
Go me, I have General Safety!

**Comment by miamagby** [comment]
Go me, I have General Safety!

**Comment by bcmt42** [comment]
Go me, I have General Safety!

**Comment by zjgt37** [comment]
Go me, I have General Safety!

**Comment by bjg5k2** [comment]
Woo woo I did a general safety
I said that right didn't I?

**Comment by djcvf** [comment]
Go me, I did a general safety

**Comment by drw994** [comment]
Go me, i already have general safety and basic machine

**Comment by kgpat** [comment]
Go me, I have general safety, basic machine, and composites.

**Comment by SethKitchen** [comment]
By now everyone should have general safety. If you do not, you are officially behind. Complete it on canvas ASAP.
