### ISSUE TITLE
Training in Machine Shop

### ISSUE THREAD

**Issue by SethKitchen** [SethKitchen/RocketDesignTeamAgilePlans#4]
Who: All of RDT
What: Take the course on the machine shop at the SDELC
When: 9/3-9/17
Where: SDELC
Why: Most of the useful things members can help with require use of tools/machinery which can only be accessed/used with machine shop training.
How: Sign up on OrgSync then show up during the specified time.

**Comment by Calebg720** [comment]
Got it!

**Comment by AndyManson** [comment]
Done!

**Comment by kczn6** [comment]
Also got it.

**Comment by Usman-B** [comment]
Got it!

**Comment by SethKitchen** [comment]
September 5: 4-7
September 7: 2-5

**Comment by jawwm9** [comment]
Got it!

**Comment by SethKitchen** [comment]
Basic Machine Shop: Tuesday at 6
