### ISSUE TITLE
Training in Lathe

### ISSUE THREAD

**Issue by SethKitchen** [SethKitchen/RocketDesignTeamAgilePlans#5]
Who: Half of propulsion
What: Take the course on lathe through the SDELC.
When: 9/17-10/1
Where: SDELC
Why: Building a motor requires use of lathe, so to complete propulsion's most critical task this is necessary.
How: Sign up on OrgSync then show up to the SDELC at the specified time.

**Comment by Calebg720** [comment]
Got it!

**Comment by AndyManson** [comment]
I've taken the training but I still need to make a part

**Comment by Usman-B** [comment]
Got it!

**Comment by ZachWeicken** [comment]
I also have the training and need to make a part, who do I need to talk to about that?

**Comment by SethKitchen** [comment]
Matt Fogle or Christian Robless or Terry McGarvey
