### ISSUE TITLE
Training in Electronics

### ISSUE THREAD

**Issue by SethKitchen** [SethKitchen/RocketDesignTeamAgilePlans#6]
Who: Half of Electronics
What: Take the course in Electronics Safety given by the SDELC.
When: 9/3-9/10
Where: SDELC
Why: Soldering, using Oscilloscopes, and grabbing parts require the electronics room only accessible through the training.
How: Sign up on OrgSync and show up at the specified time.

**Comment by Usman-B** [comment]
Got it!
