### ISSUE TITLE
Training in Composites

### ISSUE THREAD

**Issue by SethKitchen** [SethKitchen/RocketDesignTeamAgilePlans#7]
Who: Half of D&M
What: Take the course in Composites Safety through the SDELC
When: 9/17-10/1
Where: SDELC
Why: For layups, using epoxy, and composites room access composites safety training is required.
How: Sign up on OrgSync and show up at the specified time.

**Comment by Calebg720** [comment]
Got it!

**Comment by Usman-B** [comment]
Got it!
